export type Priority = 'IMPERDIBLE' | 'ALTA' | 'MEDIA' | 'LIBRE' | 'DESCANSO'
export type SessionType = 'Talk' | 'Keynote' | 'Workshop' | 'Panel' | ''
export type DayKey = 'martes' | 'miercoles' | 'jueves'

export interface SpeakerLinks {
  linkedin?: string
  twitter?: string
  website?: string
}

export interface Session {
  start: string
  end: string
  title: string
  speaker: string
  stage: string
  type: SessionType
  priority: Priority
  prediction: string
  notes: string
  speakerLinks?: SpeakerLinks
}

export interface DayData {
  key: DayKey
  label: string
  date: string
  sessions: Session[]
}

export interface Itinerary {
  key: string
  label: string
  description: string
  days: DayData[]
  stats: {
    sessions: number
    imperdibles: number
    workshops: number
    breaks: number
  }
}

// ---------------------------------------------------------------------------
// INTENSIVE ITINERARY
// ---------------------------------------------------------------------------

const intensivoMartes: Session[] = [
  {
    start: '11:00',
    end: '11:55',
    title: 'El mayor descubrimiento de la historia (Keynote)',
    speaker: 'Aythami Soto, Reacciona Espacial',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Divulgacion cientifica sobre descubrimientos recientes en astrofisica/espacio. Aythami es creador de contenido de ciencia en espanol con millones de seguidores.',
    notes: 'Entretenida pero no directamente aplicable a tu negocio. Si llegas temprano, vale la pena.',
  },
  {
    start: '11:00',
    end: '11:30',
    title: 'Defensa inteligente: como la IA esta redefiniendo la ciberseguridad',
    speaker: 'Omar Ramirez, CTO Bambu Tech',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'IA para deteccion de amenazas, SIEM con ML, automatizacion de respuesta a incidentes. Superficies de ataque en era de IA, vulnerabilidades de modelos.',
    notes: 'Ayer aprendiste sobre superficies de ataque. Esto va mas profundo en como la IA defiende y ataca. Util para vender servicios de seguridad a clientes.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'IngenierIA con consecuencias',
    speaker: 'Raul Villarreal, AI Engineer Space Apps',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Etica de IA, consecuencias no intencionadas de modelos en produccion. Sesgos, alucinaciones, responsabilidad del ingeniero.',
    notes: 'Complementa lo de Explicabilidad/Trazabilidad/Responsabilidad que aprendiste ayer. Refuerza conceptos.',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Agentes de codificacion: La nueva frontera',
    speaker: 'Andre Hernandez Borm',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Workshop practico sobre coding agents: Cursor, Claude Code, Copilot Workspace. Como configurar agentes que escriben, testean y deployean codigo de forma autonoma.',
    notes: 'ESTO ES TU MUNDO. Vibecodeas diario con Claude Code. Ve a validar tu approach y aprender trucos nuevos. Si hay algo que no conoces, es oro.',
  },
  {
    start: '12:00',
    end: '12:30',
    title: 'Marcas que Piensan: 5 tendencias de IA que ya dominan el mercado',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '5 tendencias de IA en marketing: personalizacion, contenido generativo, ads predictivos, chatbots avanzados, analisis de sentimiento. Con casos de marcas reales.',
    notes: 'Directamente aplicable a tu agencia. Heri despues da un workshop el miercoles, asi calibras si su nivel te sirve.',
  },
  {
    start: '12:30',
    end: '13:00',
    title: 'USUARIOS SINTETICOS: superpoder para construir el futuro',
    speaker: 'Ricardo Rebolledo, 2Brains/AcidLabs',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Generar usuarios sinteticos con IA para testear productos sin usuarios reales. Validar UX, flujos, hipotesis con personas generadas por LLMs.',
    notes: 'Algo que NO haces todavia y puede cambiar como validas productos para clientes. Novel y aplicable.',
  },
  {
    start: '13:00',
    end: '13:25',
    title: 'El arte de hacer que suceda (Keynote)',
    speaker: 'Fernanda Guarro, Presidenta 3M Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Keynote corporativa sobre ejecucion, cultura de innovacion en 3M, liderazgo femenino en tech.',
    notes: 'Pulida pero probablemente generica. Perspectiva de quien maneja empresa de $30B.',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'IRL is a cheat code: in-person events unlock what the internet cant',
    speaker: 'Briana Holmes, Head Community Torc',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Valor de eventos presenciales vs online. Networking strategies, community building, serendipity de conexiones IRL.',
    notes: 'Meta: estas EN un evento IRL. Si el contenido te aburre, aplica lo que dice y ve a hacer networking.',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'Playables: el formato que redefine la atencion digital',
    speaker: 'Simon Ceglarek, CEO Pixpik Studio',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Contenido interactivo (playable ads, mini-games en marketing). Como las marcas usan gamificacion para engagement. Metricas vs video/banners.',
    notes: 'Formato nuevo para ofrecer a clientes de ACID MKT. Diferenciador real si lo implementas.',
  },
  {
    start: '14:30',
    end: '14:55',
    title: 'La Era Exponencial',
    speaker: 'Arnau Ramio, Co-Founder Learning Heroes',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Crecimiento exponencial de tecnologia, como adaptarse, mentalidad de aprendizaje continuo.',
    notes: 'Charla motivacional con datos. Buena para resetear perspectiva si estas saturado de charlas tacticas.',
  },
  {
    start: '15:00',
    end: '16:00',
    title: 'WORKSHOP: Deja de hacer click ops con Serverless Framework',
    speaker: 'Christian Medinilla, CTO Holy Tech',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Infrastructure as Code con Serverless Framework. Deploy Lambdas, APIs, sin hacer click en consolas. CI/CD automatizado.',
    notes: 'Si haces click ops para deployear cosas de clientes, esto te ahorra horas. Medinilla da otra charla el jueves sobre ciberseguridad.',
  },
  {
    start: '16:00',
    end: '16:30',
    title: 'Radical Innovation',
    speaker: 'Arturo Portillo, Dir. Estrategia Platzi',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Framework de innovacion radical de Platzi. Como salir del incremental improvement. Metodologias para disrumpir.',
    notes: 'Platzi es referente LATAM en edtech. Arturo ve tendencias de mercado de primera mano. Escucha que ven venir.',
  },
  {
    start: '16:30',
    end: '17:00',
    title: 'Automatizacion para negocios',
    speaker: 'Jose Luis Cruz, Founder BeTrep',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Herramientas no-code/low-code para automatizar procesos de negocio. Zapier, Make, N8N a nivel basico.',
    notes: 'Probablemente nivel introductorio. Si ya automatizas, saltalo.',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'De experto a formador: multiplica tu hora x20 (Keynote)',
    speaker: 'Pablo Herreros',
    stage: 'Business Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Como empaquetar expertise en cursos/programas online. Modelo de negocio de infoproductos. Pricing de conocimiento.',
    notes: 'Relevante si estas pensando en productizar conocimiento de ACID MKT. Pasar de vender horas a vender sistemas.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'De Zero a Digital: 90 dias para automatizar tu operacion',
    speaker: 'Panel Melius Services',
    stage: 'Business Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: 'Caso de estudio de digitalizacion de empresa tradicional en 90 dias. Herramientas, resistencia al cambio, ROI.',
    notes: 'Util si tienes clientes que necesitan digitalizarse. Framework de 90 dias es vendible.',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La IA fue solo el inicio, preparate para lo que viene',
    speaker: 'Guillermo Perezbolde, CEO Mente Digital',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Tendencias post-IA: computacion espacial, agentes autonomos, interfaces cerebro-maquina. Perezbolde es referente de marketing digital MX.',
    notes: 'Solo 25 min y Perezbolde es solido. Buena relacion tiempo/valor.',
  },
  {
    start: '18:30',
    end: '19:00',
    title: 'IA Low Code: prototipos para clientes',
    speaker: 'Cesar Salinas, Co-Fundador Datlas',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Prototipar apps de IA con herramientas low-code. Streamlit, Gradio, Vercel AI SDK para demos rapidos a clientes.',
    notes: 'Podria darte ideas para hacer demos mas rapido para clientes de la agencia.',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'IA y Vibecoding para automatizar de forma efectiva',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Como usa Cursor/Claude/Copilot para automatizar procesos internos de Raiola (hosting con miles de clientes). Workflows de vibecoding aplicados a operaciones reales.',
    notes: 'Tu ya vibecodeeas a nivel avanzado. La perspectiva de alguien que lo aplica a escala de empresa de hosting es valiosa.',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'Mas alla del Monolito: Microservicios exitosos',
    speaker: 'Ivan Carrillo, Staff SWE en WGU',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Patrones de migracion monolito a microservicios. Cuando si y cuando no. Errores comunes.',
    notes: 'Mas arquitectura enterprise. Util si escalas proyectos de clientes grandes.',
  },
  {
    start: '22:00',
    end: '22:55',
    title: 'No todo es Black Mirror (Keynote)',
    speaker: 'Ophelia Pastrana',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Vision optimista de la tecnologia: oportunidades de IA, derechos digitales, transhumanismo. Entretenida, provocadora.',
    notes: 'No vas a aprender herramientas pero Ophelia te hace pensar diferente. Si estas cansado, mejor duerme.',
  },
]

const intensivoMiercoles: Session[] = [
  {
    start: '11:00',
    end: '11:55',
    title: 'Mision: Interstellar (Keynote)',
    speaker: 'Javier Santaolalla, Fisico y Divulgador',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Divulgacion cientifica de primer nivel. Fisica de particulas, cosmos, fronteras del conocimiento humano. Javier tiene millones de seguidores por algo — hace la ciencia accesible y emocionante.',
    notes: 'No es aplicable a tu negocio pero es el tipo de charla que te expande la mente. Arranca el dia con inspiracion real.',
  },
  {
    start: '11:00',
    end: '11:30',
    title: 'Como usar la IA para vender mas con tus anuncios',
    speaker: 'Luis Flores, Google Ads Specialist',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Performance Max, Smart Bidding, ChatGPT/Claude para copys de anuncios, testing creativo con IA, optimizacion de audiencias con ML de Google.',
    notes: 'Puede que ya conozcas las features de Google Ads AI. Lo valioso seria ver si tiene un framework de testing creativo que tu no uses.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'Liderar equipos en remoto con IA sin perder lo humano',
    speaker: 'Irene Toledano, CEO Avanza Digital',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Herramientas de IA para gestion de equipos remotos. Cultura de equipo, comunicacion asincrona, productividad sin micromanagement.',
    notes: 'Si manejas equipo remoto en ACID MKT, puede darte frameworks utiles.',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Una charla con Uri Sabat (Keynote)',
    speaker: 'Uri Sabat, CEO The Santos Club',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Formato entrevista. The Santos Club es marca lifestyle/streetwear mexicana exitosa. Como construyo la marca, estrategia de comunidad, decision-making.',
    notes: 'Uri construyo una marca que genera comunidad real, no solo ventas. Aplica a como posicionas ACID MKT.',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Proyectos que Hacen Destacar a Cualquier Developer',
    speaker: 'Hazel Saenz & Axel Espinosa, AWS',
    stage: 'Developer Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: 'Proyectos que impresionan en portfolio de developer. Uso de AWS services para proyectos personales. Cloud projects que demuestran skills.',
    notes: 'Mas para developers buscando empleo. Saltalo si ya tienes tu agencia corriendo.',
  },
  {
    start: '13:00',
    end: '13:25',
    title: 'Sin pilas, sin cables: el futuro de la energia cinetica',
    speaker: 'Elizabeth Villareal (Eila)',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Innovacion en energia cinetica, cosecha de energia del movimiento humano. Wearables autosuficientes, IoT sin baterias.',
    notes: 'Fascinante pero no aplicable directamente. Ve si te interesa hardware/IoT.',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'No construyas prompts. Construye sistemas con IA',
    speaker: 'David Fernandez, TDM Internacional',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Ir mas alla de prompt engineering. Arquitectura de sistemas con IA: pipelines, chain of thought sistematizado, RAG, function calling. El prompt es solo una pieza.',
    notes: 'ESTO ES CLAVE. Pasar de prompts sueltos a sistemas replicables es lo que te va a escalar.',
  },
  {
    start: '13:30',
    end: '14:25',
    title: 'Resiliencia financiera: Que hacer cuando quieres renunciar a ser adulto (Keynote)',
    speaker: 'Sofia Macias, Pequeno Cerdo Capitalista',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Finanzas personales para emprendedores. Como manejar la incertidumbre financiera, invertir mientras emprendes, psicologia del dinero.',
    notes: 'Sofia es la referente #1 de finanzas personales en Mexico. Si tu situacion financiera te estresa, esta charla es terapia con datos.',
  },
  {
    start: '14:00',
    end: '15:00',
    title: 'WORKSHOP: Decision-First Ideation con IA',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'ALTA',
    prediction: 'Framework para usar IA en ideacion de productos/campanas. Tomar decisiones primero, luego usar IA para validar y ejecutar.',
    notes: 'Metodologia directamente aplicable a como presentas ideas a clientes.',
  },
  {
    start: '15:00',
    end: '15:30',
    title: 'El camino a la superinteligencia',
    speaker: 'Glenda Michel, Futuros Humanos',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Timeline de IA hacia AGI/ASI. Implicaciones economicas, sociales, existenciales. Que hacer como humanos ante la singularidad.',
    notes: 'Charla de perspectiva amplia. No tactica pero te ayuda a pensar a largo plazo.',
  },
  {
    start: '15:30',
    end: '15:55',
    title: 'Como sobrevivir a una IA que intenta sustituirte (Keynote)',
    speaker: 'MoureDev (Brais Moure)',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: 'MoureDev tiene 2M+ suscriptores tech. Habilidades humanas irremplazables, como adaptarse, experiencia usando IA en desarrollo.',
    notes: 'Moure vive de ensenar tech y usa IA diario. State of the union desde las trincheras.',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'WORKSHOP: De cero a tu servidor de automatizaciones con N8N',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Setup de N8N self-hosted (Docker). Crear workflows de automatizacion: webhooks, integraciones con APIs, triggers, scheduling.',
    notes: 'N8N es complementario a tu vibecoding. Para tareas repetitivas N8N > escribir codigo custom cada vez.',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'Business OS: IA Reemplazo a Mi Equipo y Triplico Resultados',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Que roles reemplazo con IA, que herramientas uso, metricas antes/despues. SOPs convertidos en prompts sistematizados, agentes para customer service.',
    notes: 'ESTE ES EL SPEAKER DEL EVENTO PARA TI. Hace exactamente lo que quieres hacer con ACID MKT. Habla con el despues.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'Agentes de IA sin Humo: Implementarlos Sin Romper Tu Empresa',
    speaker: 'Gerardo Pineda, Dir. Intel. Datos CONTPAQi',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'CONTPAQi es EL software contable de Mexico. Que funciono y que no al meter agentes. Resistencia organizacional, casos reales, errores costosos.',
    notes: 'Perspectiva enterprise mexicana. Como metieron agentes en software que usan 600k+ empresas sin romper nada.',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La era de los AInfluencers',
    speaker: 'AItana Lopez, CEO @theclueless.ai',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Influencers generados por IA: modelos virtuales, content creators sinteticos. Negocio detras, etica, futuro del influencer marketing.',
    notes: 'AItana es literalmente una influencer de IA. Esto cambia el juego del marketing de influencers para tus clientes.',
  },
  {
    start: '18:30',
    end: '19:00',
    title: 'Software Engineering Excellence at Global Scale',
    speaker: 'Panel Directors of Engineering McDonald\'s',
    stage: 'Developer Stage',
    type: 'Panel',
    priority: 'ALTA',
    prediction: 'Como McDonald\'s maneja desarrollo a escala global. Arquitectura, equipos distribuidos, CI/CD a nivel enterprise, cultura de ingenieria.',
    notes: 'Perspectiva de empresa Fortune 500. Aprende como piensan los grandes para escalar.',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'Agentes en produccion: automatizacion con guardrails y metricas',
    speaker: 'Jorge Bojorges, Founder D3sconocidos',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Como correr agentes autonomos en produccion. Guardrails, metricas (latencia, costo, accuracy), monitoreo, fallbacks. LangChain/CrewAI + observability.',
    notes: 'El como tactico que falta despues de charlas conceptuales. Si vas a poner agentes para clientes, necesitas esto.',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'Como poner a trabajar un LLM localmente',
    speaker: 'Victor Moreno, Software Architect BRITA AI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Ollama, llama.cpp, modelos open source locales. Privacy, costos reducidos, fine-tuning local. Setup practico.',
    notes: 'LLMs locales para datos sensibles de clientes. Cada vez mas viable y necesario.',
  },
  {
    start: '20:00',
    end: '20:25',
    title: 'IA Agentica: Mas Alla del Prompt',
    speaker: 'Jorge Paz, IBM Data & AI Expert',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Vision de IBM sobre agentic AI. Multi-agentes, orquestacion, tool use. IBM watsonx perspective.',
    notes: 'Vision enterprise de agentes. Puede sentirse abstracto despues de Bojorges.',
  },
  {
    start: '21:00',
    end: '21:55',
    title: 'Entrevista con Marcus Dantus (Keynote)',
    speaker: 'Marcus Dantus, Fundador StartUp Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Ecosistema startup mexicano. Vision, errores comunes, que buscan inversionistas. Marcus es polemico y directo.',
    notes: 'Si te interesa inversion/startups en Mexico, no hay nadie que lo conozca mejor.',
  },
]

const intensivoJueves: Session[] = [
  {
    start: '11:00',
    end: '11:25',
    title: 'IA sin filtro: burbuja, dilemas eticos y el futuro del talento humano',
    speaker: 'Panel: Bianca Ivan Espinosa, Eddie Robinson',
    stage: 'Main Stage',
    type: 'Panel',
    priority: 'ALTA',
    prediction: 'Debate sin censura sobre burbuja de IA, dilemas eticos reales, que pasa con los empleos. Perspectivas encontradas.',
    notes: 'Panel honesto vs el hype de IA de las demas charlas. Buena dosis de realidad para arrancar el dia.',
  },
  {
    start: '11:00',
    end: '11:30',
    title: 'ViveCoding: El despertar del programador en la era de la IA',
    speaker: 'Oscar Armas, Sr MLOps LexisNexis / JunoAI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Como cambia el rol del developer con IA. De escribir codigo a orquestar agentes, MLOps como disciplina, QA de codigo generado por IA.',
    notes: 'Doble perfil enterprise + startup. Probablemente mas avanzado que el vibecoding de Fontela.',
  },
  {
    start: '11:30',
    end: '11:55',
    title: 'Romper moldes: liderar la transformacion en tiempos de cambio',
    speaker: 'Adama Gonzalez',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Liderazgo en tiempos de disrupcion tecnologica. Change management, adaptabilidad organizacional.',
    notes: 'Charla de liderazgo. Util si lideras equipo, generica si no.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'Mas alla del Phishing: Tu codigo como primera linea de defensa',
    speaker: 'Christian Medinilla, CTO Holy Tech',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Seguridad en codigo: OWASP top 10, secure coding practices, supply chain attacks en npm/pip. Tu codigo ES la superficie de ataque.',
    notes: 'Medinilla dio el workshop de Serverless ayer. Ahora va a seguridad. Complementario.',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'IA valio? Como sobrevivir en la era de la IA (Keynote)',
    speaker: 'Juan Lombana, CEO Mercatitlan',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Que IA funciona en e-commerce real, que es hype, como una PYME mexicana puede competir con IA. Pragmatico y con datos.',
    notes: 'Perspectiva de negocio real mexicano, no de Silicon Valley.',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Recursividad Agentica: Deja de Ser el Cuello de Botella de la IA',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Parte 2 de Business OS. Agentes que lanzan otros agentes, loops de mejora autonoma, el humano como supervisor.',
    notes: 'ESTO ES LO QUE YA HACES CON GSD + Claude Code. Carreon lo aplica a operaciones de negocio. Intercambia notas con el.',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'EL FIN DE LA SUMA: despedir para automatizar es un error',
    speaker: 'Celeste Torresi, CCO Santex',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Contra-argumento al reemplazo de empleados por IA. Augmentation > replacement. Casos donde automatizar sin despedir triplico valor.',
    notes: 'Perspectiva importante. No todo es reemplazar. A veces potenciar empleados da mas ROI.',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'Hackers, IA y fintech: la nueva guerra digital',
    speaker: 'Irving Sanchez, Head of Product Conecta',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Ciberseguridad en fintech: IA para fraude, deepfakes en KYC, ataques a APIs financieras. La guerra IA vs IA en seguridad.',
    notes: 'Si tienes clientes fintech o quieres entrar al sector, esta charla es key.',
  },
  {
    start: '15:30',
    end: '16:00',
    title: 'Como disenar tu carrera en la economia de la IA',
    speaker: 'Panel Utel + IPN',
    stage: 'Developer Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: 'Habilidades demandadas, carreras emergentes, certificaciones que valen vs las que no. Perspectiva academica.',
    notes: 'Mas para quienes buscan empleo. Tu ya tienes tu camino.',
  },
  {
    start: '16:00',
    end: '16:55',
    title: 'Tu Carrera en la Era de la IA',
    speaker: 'Martha Cuevas, LinkedIn Dir. Hispanic LATAM',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'DATOS de LinkedIn sobre mercado laboral. Skills demandados, industrias creciendo, como IA cambia contrataciones.',
    notes: 'No es sobre TU carrera, es sobre ENTENDER EL MERCADO. Util para posicionar tu agencia.',
  },
  {
    start: '17:00',
    end: '18:00',
    title: 'WORKSHOP: Disena Proyectos de IA de Mas de $1 Millon',
    speaker: 'Carlos Chiang, CEO Neurotry',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Como scopear proyectos grandes de IA, estructura de propuesta, pricing, gestion de stakeholders, entregables.',
    notes: 'Si Chiang trabaja con MeLi en IA, su framework te puede subir el ticket de ACID MKT.',
  },
  {
    start: '18:00',
    end: '19:25',
    title: 'AI LIDERAZGO: El futuro del liderazgo es COCO (Keynote)',
    speaker: 'Vilma Nunez, Founder @conviertemas',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: 'Como liderar equipos/empresas de marketing con IA. COCO = framework suyo. Vision del futuro de agencias.',
    notes: 'Vilma tiene tu modelo de negocio a escala masiva. Lo que ella hizo con su agencia es el playbook para ACID MKT.',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'UX y AI: el nuevo motor del crecimiento empresarial',
    speaker: 'Maria de Buen, CEO BluePixel',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Como IA mejora UX research, testing, personalizacion. Design systems con IA. Growth through better UX.',
    notes: 'Si ofreces UX a clientes, vale la pena. Si no, saltalo.',
  },
  {
    start: '21:00',
    end: '00:25',
    title: 'Un podcast con Jordi Wild (Keynote)',
    speaker: 'Jordi Wild, The Wild Project',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Podcast en vivo 3+ hrs. Estilo Joe Rogan. No se sabe el invitado. Entretenimiento puro.',
    notes: 'TOTALMENTE OPCIONAL. Si no estas muerto despues de 3 dias, puede ser divertido.',
  },
]

// ---------------------------------------------------------------------------
// RELAXED ITINERARY
// ---------------------------------------------------------------------------

const relajadoMartes: Session[] = [
  {
    start: '11:00',
    end: '12:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Llegas tranquilo. Cafe, ubicate, recorre la expo. El keynote de Main Stage es de ciencia (Aythami Soto) — entretenido pero no urgente.',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Agentes de codificacion: La nueva frontera',
    speaker: 'Andre Hernandez Borm',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Workshop practico sobre coding agents: Cursor, Claude Code, Copilot Workspace. Como configurar agentes que escriben, testean y deployean codigo autonomamente.',
    notes: 'TU TEMA. Valida tu approach de vibecoding y aprende trucos nuevos. Si solo vas a una cosa hoy, que sea esta.',
  },
  {
    start: '12:00',
    end: '12:30',
    title: 'Marcas que Piensan: 5 tendencias de IA en el mercado',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '5 tendencias de IA en marketing: personalizacion, contenido generativo, ads predictivos, chatbots, analisis de sentimiento. Con casos de marcas mexicanas.',
    notes: 'Directamente aplicable a tu agencia. Heri despues da un workshop el miercoles, asi calibras si su nivel te sirve.',
  },
  {
    start: '12:30',
    end: '13:00',
    title: 'USUARIOS SINTETICOS: superpoder para construir y probar el futuro',
    speaker: 'Ricardo Rebolledo, 2Brains/AcidLabs',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Generar usuarios sinteticos con IA para testear productos sin usuarios reales. Validar UX, flujos, hipotesis de mercado con personas generadas por LLMs.',
    notes: 'Esto es algo que NO haces todavia y que puede cambiar como validas los productos que construyes para clientes. Novel y aplicable.',
  },
  {
    start: '13:00',
    end: '13:25',
    title: 'El arte de hacer que suceda (Keynote)',
    speaker: 'Fernanda Guarro, Presidenta 3M Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Keynote corporativa sobre ejecucion, cultura de innovacion en 3M, liderazgo.',
    notes: 'HONESTAMENTE: puede sonar a corporativo generico. Ve si te interesa la perspectiva de alguien que maneja una empresa de $30B, si no, extiende la comida.',
  },
  {
    start: '13:25',
    end: '15:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO. Come bien. Haz networking en zona de comida.',
  },
  {
    start: '15:00',
    end: '16:00',
    title: 'WORKSHOP: Deja de hacer click ops con Serverless Framework',
    speaker: 'Christian Medinilla, CTO Holy Tech',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Infrastructure as Code con Serverless Framework. Deploy Lambdas, APIs sin consola. CI/CD automatizado.',
    notes: 'Si haces click ops para deployear, esto te ahorra horas semanales. Practico y hands-on.',
  },
  {
    start: '16:00',
    end: '16:30',
    title: 'Radical Innovation',
    speaker: 'Arturo Portillo, Dir. Estrategia Platzi',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Framework de innovacion radical de Platzi. Metodologias para disrumpir, no solo mejorar incrementalmente.',
    notes: 'Platzi ve tendencias LATAM de primera mano. Escucha que ven venir para 2026-2027.',
  },
  {
    start: '16:30',
    end: '17:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso / cafe / siesta',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'De experto a formador: multiplica tu hora x20 (Keynote)',
    speaker: 'Pablo Herreros',
    stage: 'Business Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Como empaquetar tu expertise en cursos/programas online. Modelo de negocio de infoproductos. Pricing de conocimiento.',
    notes: 'Relevante si estas pensando en productizar el conocimiento de ACID MKT. Pasar de vender horas a vender sistemas.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso largo antes del bloque de la noche',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La IA fue solo el inicio, preparate para lo que viene',
    speaker: 'Guillermo Perezbolde, CEO Mente Digital',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Tendencias post-IA: computacion espacial, agentes autonomos, interfaces cerebro-maquina. Perezbolde es referente del marketing digital MX.',
    notes: 'Solo 25 min y Perezbolde es solido. Buena relacion tiempo/valor.',
  },
  {
    start: '18:25',
    end: '19:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'IA y Vibecoding para automatizar de forma efectiva',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Fontela maneja Raiola (hosting espanol con miles de clientes). Como usa Cursor/Claude/Copilot para automatizar procesos internos.',
    notes: 'OJO: Tu ya vibecodeeas a nivel avanzado con Claude Code + GSD. Puede que el nivel sea menor al tuyo. PERO la perspectiva de alguien que lo aplica a escala es valiosa.',
  },
  {
    start: '19:30',
    end: '22:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cena tranquila. Lo que sigue es OPCIONAL',
  },
  {
    start: '22:00',
    end: '22:55',
    title: 'No todo es Black Mirror (Keynote)',
    speaker: 'Ophelia Pastrana',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Vision optimista de la tecnologia: oportunidades de IA, derechos digitales, transhumanismo. Entretenida, provocadora, nada tecnica.',
    notes: 'OPCIONAL. No vas a aprender herramientas pero Ophelia te hace pensar diferente. Si estas cansado, mejor duerme.',
  },
]

const relajadoMiercoles: Session[] = [
  {
    start: '11:00',
    end: '11:55',
    title: 'Mision: Interstellar (Keynote)',
    speaker: 'Javier Santaolalla, Fisico y Divulgador',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Divulgacion cientifica de primer nivel sobre el cosmos y la fisica de particulas. Javier tiene millones de seguidores — hace la ciencia accesible y emocionante.',
    notes: 'No es aplicable a tu negocio pero te expande la mente. Arranca el dia con inspiracion real, no con una charla mas de IA.',
  },
  {
    start: '11:00',
    end: '11:30',
    title: 'Como usar la IA para vender mas con tus anuncios',
    speaker: 'Luis Flores, Google Ads Specialist',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Performance Max, Smart Bidding, ChatGPT/Claude para copys de anuncios, testing creativo con IA.',
    notes: 'Puede que ya conozcas las features de Google Ads AI. Lo valioso seria ver si tiene un framework de testing creativo que tu no uses.',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Una charla con Uri Sabat (Keynote)',
    speaker: 'Uri Sabat, CEO The Santos Club',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Formato entrevista con Uri Sabat. The Santos Club es marca lifestyle/streetwear mexicana exitosa.',
    notes: 'Uri construyo una marca que genera comunidad real, no solo ventas. Esa mentalidad aplica a como posicionas ACID MKT.',
  },
  {
    start: '13:00',
    end: '14:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO. Come bien. Si puedes, invita a algun speaker a comer.',
  },
  {
    start: '13:30',
    end: '14:25',
    title: 'Resiliencia financiera (Keynote)',
    speaker: 'Sofia Macias, Pequeno Cerdo Capitalista',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Finanzas personales para emprendedores. Incertidumbre financiera, invertir mientras emprendes, psicologia del dinero.',
    notes: 'Sofia es LA referente de finanzas en Mexico. Si emprender te estresa financieramente, esta es terapia con datos.',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion suave',
  },
  {
    start: '14:30',
    end: '15:00',
    title: 'Mas alla del SEO: Posicionamiento en el ecosistema de las IA',
    speaker: 'Erick Zendejas, Co-Founder Student Xperience',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Como posicionarse en ChatGPT, Perplexity, Gemini — no solo Google. SEO para LLMs: schema markup, E-E-A-T en contexto de IA.',
    notes: 'ESTO ES NUEVO y directamente aplicable. Tu agencia hace SEO y esto es el siguiente paso que pocos conocen.',
  },
  {
    start: '15:00',
    end: '15:30',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Preparate para el keynote',
  },
  {
    start: '15:30',
    end: '15:55',
    title: 'Como sobrevivir a una IA que intenta sustituirte (Keynote)',
    speaker: 'MoureDev (Brais Moure)',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: 'MoureDev tiene 2M+ suscriptores tech. Habilidades humanas irremplazables, como adaptarse, su experiencia usando IA.',
    notes: 'No esperes herramientas nuevas. Es mas un state of the union desde alguien que vive de ensenar tech.',
  },
  {
    start: '15:55',
    end: '16:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: '',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'WORKSHOP: De cero a tu servidor de automatizaciones con N8N',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Setup de N8N self-hosted (Docker). Crear workflows de automatizacion: webhooks, integraciones con APIs, triggers, scheduling.',
    notes: 'N8N es complementario a tu vibecoding, no competencia. Para tareas repetitivas N8N > escribir codigo custom cada vez.',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'Business OS: IA Reemplazo a Mi Equipo y Triplico Resultados',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Que roles reemplazo con IA, que herramientas uso, metricas antes/despues. SOPs convertidos en prompts sistematizados.',
    notes: 'ESTE ES EL SPEAKER DEL EVENTO PARA TI. Hace exactamente lo que quieres hacer con ACID MKT. Habla con el despues.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'Agentes de IA sin Humo: Implementarlos Sin Romper Tu Empresa',
    speaker: 'Gerardo Pineda, Dir. Intel. Datos CONTPAQi',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'CONTPAQi es EL software contable de Mexico. Que funciono y que no al meter agentes en empresa establecida.',
    notes: 'Perspectiva enterprise mexicana. Como metieron agentes en software que usan 600k+ empresas sin romper nada.',
  },
  {
    start: '18:00',
    end: '19:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'CENA TEMPRANA. Recarga para el cierre.',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'Agentes en produccion: automatizacion con guardrails y metricas',
    speaker: 'Jorge Bojorges, Founder D3sconocidos',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Como correr agentes autonomos en produccion. Guardrails, metricas (latencia, costo, accuracy), monitoreo, fallbacks.',
    notes: 'El como tactico que falta despues de charlas conceptuales. Si vas a poner agentes para clientes, necesitas esto.',
  },
  {
    start: '19:30',
    end: '20:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion',
  },
  {
    start: '20:00',
    end: '20:25',
    title: 'IA Agentica: Mas Alla del Prompt',
    speaker: 'Jorge Paz, IBM Data & AI Expert',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Vision de IBM sobre agentic AI. Multi-agentes, orquestacion, tool use.',
    notes: 'HONESTAMENTE: despues de la charla de Bojorges esto puede sentirse abstracto. Si estas cansado, saltalo.',
  },
  {
    start: '20:25',
    end: '21:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Puedes irte. Marcus es opcional',
  },
  {
    start: '21:00',
    end: '21:55',
    title: 'Entrevista con Marcus Dantus (Keynote)',
    speaker: 'Marcus Dantus, Fundador StartUp Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Entrevista sobre ecosistema startup mexicano. Vision, errores comunes, que buscan inversionistas.',
    notes: 'OPCIONAL. Si te interesa inversion/startups en Mexico, no hay nadie que lo conozca mejor.',
  },
]

const relajadoJueves: Session[] = [
  {
    start: '11:00',
    end: '11:25',
    title: 'IA sin filtro: burbuja, dilemas eticos y futuro del talento',
    speaker: 'Panel: Bianca Ivan Espinosa, Eddie Robinson',
    stage: 'Main Stage',
    type: 'Panel',
    priority: 'ALTA',
    prediction: 'Debate sin censura sobre la burbuja de IA, dilemas eticos reales, y que pasa con los empleos. Perspectivas encontradas.',
    notes: 'Dosis de realidad despues de 2 dias de hype de IA. Arranca el dia con honestidad.',
  },
  {
    start: '11:00',
    end: '11:30',
    title: 'ViveCoding: El despertar del programador en la era de la IA',
    speaker: 'Oscar Armas, Sr MLOps LexisNexis / JunoAI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Como cambia el rol del developer con IA, de escribir codigo a orquestar agentes, MLOps como disciplina, QA de codigo generado por IA.',
    notes: 'Su doble perfil enterprise + startup le da perspectiva unica. Probablemente mas avanzado que el vibecoding de Fontela.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cafe, ultimo recorrido por la expo',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'IA valio? Como sobrevivir en la era de la IA (Keynote)',
    speaker: 'Juan Lombana, CEO Mercatitlan',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Que IA funciona en e-commerce real, que es hype, como una PYME mexicana puede competir con IA. Pragmatico y con datos.',
    notes: 'Perspectiva de negocio real mexicano, no de Silicon Valley.',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Recursividad Agentica: Deja de Ser el Cuello de Botella de la IA',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Parte 2 de Business OS. Agentes que lanzan otros agentes, loops de mejora autonoma, el humano como supervisor.',
    notes: 'ESTO ES LO QUE YA HACES CON GSD + Claude Code. La diferencia es que Carreon lo aplica a operaciones de negocio. Habla con el despues, intercambia notas.',
  },
  {
    start: '13:30',
    end: '15:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO LARGO. Ultimo dia. Come bien, intercambia contactos, despidete de la expo.',
  },
  {
    start: '15:00',
    end: '16:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso largo. Alternativa: panel de carrera en Developer Stage (15:30)',
  },
  {
    start: '16:00',
    end: '16:55',
    title: 'Tu Carrera en la Era de la IA',
    speaker: 'Martha Cuevas, LinkedIn Dir. Hispanic LATAM',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'DATOS de LinkedIn sobre mercado laboral. Skills demandados, industrias creciendo, como IA cambia contrataciones.',
    notes: 'No es sobre TU carrera, es sobre ENTENDER EL MERCADO. Util para posicionar tu agencia.',
  },
  {
    start: '16:55',
    end: '17:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: '',
  },
  {
    start: '17:00',
    end: '18:00',
    title: 'WORKSHOP: Disena Proyectos de IA de Mas de $1 Millon',
    speaker: 'Carlos Chiang, CEO Neurotry',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Como scopear proyectos grandes de IA, estructura de propuesta, pricing, gestion de stakeholders.',
    notes: 'OJO: $1 Millon puede ser clickbait. PERO si Chiang trabaja con MeLi en IA, su framework es lo que necesitas para subir el ticket de ACID MKT.',
  },
  {
    start: '18:00',
    end: '19:25',
    title: 'AI LIDERAZGO: El futuro del liderazgo es COCO (Keynote)',
    speaker: 'Vilma Nunez, Founder @conviertemas y @vilma.ai',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: 'Como liderar equipos/empresas de marketing con IA, como transformo su operacion. COCO = framework suyo.',
    notes: 'Vilma tiene tu modelo de negocio a escala masiva. Lo que ella hizo con su agencia es el playbook para ACID MKT.',
  },
  {
    start: '19:25',
    end: '20:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Respira. Cierre oficial.',
  },
  {
    start: '20:00',
    end: '21:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cena de cierre. Celebra.',
  },
  {
    start: '21:00',
    end: '00:25',
    title: 'Un podcast con Jordi Wild',
    speaker: 'Jordi Wild, The Wild Project',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Podcast en vivo 3+ hrs. Estilo Joe Rogan. No se sabe el invitado. Entretenimiento puro.',
    notes: 'TOTALMENTE OPCIONAL. Si no estas muerto despues de 3 dias, puede ser divertido.',
  },
]

// ---------------------------------------------------------------------------
// Assembled itineraries
// ---------------------------------------------------------------------------

export const intensivo: Itinerary = {
  key: 'intensivo',
  label: 'Intenso',
  description: '53 sesiones sin parar. Maximo aprendizaje, minimo descanso.',
  days: [
    {
      key: 'martes',
      label: 'Martes',
      date: 'Abril 7',
      sessions: intensivoMartes,
    },
    {
      key: 'miercoles',
      label: 'Miercoles',
      date: 'Abril 8',
      sessions: intensivoMiercoles,
    },
    {
      key: 'jueves',
      label: 'Jueves',
      date: 'Abril 9',
      sessions: intensivoJueves,
    },
  ],
  stats: {
    sessions: 53,
    imperdibles: 12,
    workshops: 5,
    breaks: 0,
  },
}

export const relajado: Itinerary = {
  key: 'relajado',
  label: 'Relajado',
  description: '30 sesiones clave con descansos, comida y networking.',
  days: [
    {
      key: 'martes',
      label: 'Martes',
      date: 'Abril 7',
      sessions: relajadoMartes,
    },
    {
      key: 'miercoles',
      label: 'Miercoles',
      date: 'Abril 8',
      sessions: relajadoMiercoles,
    },
    {
      key: 'jueves',
      label: 'Jueves',
      date: 'Abril 9',
      sessions: relajadoJueves,
    },
  ],
  stats: {
    sessions: 30,
    imperdibles: 10,
    workshops: 3,
    breaks: 4,
  },
}

export const itineraries: Record<string, Itinerary> = {
  intensivo,
  relajado,
}
