export type Priority = 'IMPERDIBLE' | 'ALTA' | 'MEDIA' | 'LIBRE' | 'DESCANSO'
export type SessionType = 'Talk' | 'Keynote' | 'Workshop' | 'Panel' | ''
export type DayKey = 'martes' | 'miercoles' | 'jueves'

export interface SpeakerLinks {
  linkedin?: string
  twitter?: string
  website?: string
}

export interface Session {
  start: string
  end: string
  title: string
  speaker: string
  stage: string
  type: SessionType
  priority: Priority
  prediction: string
  notes: string
  speakerLinks?: SpeakerLinks
}

export interface DayData {
  key: DayKey
  label: string
  date: string
  sessions: Session[]
}

export interface Itinerary {
  key: string
  label: string
  description: string
  days: DayData[]
  stats: {
    sessions: number
    imperdibles: number
    workshops: number
    breaks: number
  }
}

// ---------------------------------------------------------------------------
// INTENSIVE ITINERARY -- 41 sessions
// ---------------------------------------------------------------------------

const intensivoMartes: Session[] = [
  {
    start: '11:00',
    end: '11:30',
    title: 'Defensa inteligente: como la IA esta redefiniendo la ciberseguridad',
    speaker: 'Omar Ramirez, CTO Bambu Tech',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'IngenierIA con consecuencias',
    speaker: 'Raul Villarreal, AI Engineer Space Apps',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '12:00',
    end: '12:30',
    title: 'Marcas que Piensan: 5 tendencias de IA en el mercado',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '12:30',
    end: '13:00',
    title: 'USUARIOS SINTETICOS: superpoder para construir el futuro',
    speaker: 'Ricardo Rebolledo, 2Brains/AcidLabs',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '13:00',
    end: '13:25',
    title: 'El arte de hacer que suceda (Keynote)',
    speaker: 'Fernanda Guarro, Presidenta 3M Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'IRL is a cheat code: in-person events unlock what the internet cant',
    speaker: 'Briana Holmes, Head Community Torc',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'Playables: el formato que redefine la atencion digital',
    speaker: 'Simon Ceglarek, CEO Pixpik Studio',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '14:30',
    end: '14:55',
    title: 'La Era Exponencial',
    speaker: 'Arnau Ramio, Co-Founder Learning Heroes',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '15:00',
    end: '16:00',
    title: 'WORKSHOP: Deja de hacer click ops con Serverless Framework',
    speaker: 'Christian Medinilla, CTO Holy Tech',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '16:00',
    end: '16:30',
    title: 'Radical Innovation',
    speaker: 'Arturo Portillo, Dir. Estrategia Platzi',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '16:30',
    end: '17:00',
    title: 'Automatizacion para negocios',
    speaker: 'Jose Luis Cruz, Founder BeTrep',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'De experto a formador: multiplica tu hora x20 (Keynote)',
    speaker: 'Pablo Herreros',
    stage: 'Business Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'De Zero a Digital: 90 dias para automatizar tu operacion',
    speaker: 'Panel Melius Services',
    stage: 'Business Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La IA fue solo el inicio, preparate para lo que viene',
    speaker: 'Guillermo Perezbolde, CEO Mente Digital',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '18:30',
    end: '19:00',
    title: 'IA Low Code: prototipos para clientes',
    speaker: 'Cesar Salinas, Co-Fundador Datlas',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'IA y Vibecoding para automatizar de forma efectiva',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'Mas alla del Monolito: Microservicios exitosos',
    speaker: 'Ivan Carrillo, Staff SWE en WGU',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '22:00',
    end: '22:55',
    title: 'No todo es Black Mirror (Keynote)',
    speaker: 'Ophelia Pastrana',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
]

const intensivoMiercoles: Session[] = [
  {
    start: '11:00',
    end: '11:30',
    title: 'Como usar la IA para vender mas con tus anuncios',
    speaker: 'Luis Flores, Google Ads Specialist',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'Liderar equipos en remoto con IA sin perder lo humano',
    speaker: 'Irene Toledano, CEO Avanza Digital',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Una charla con Uri Sabat (Keynote)',
    speaker: 'Uri Sabat, CEO The Santos Club',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Proyectos que Hacen Destacar a Cualquier Developer',
    speaker: 'Hazel Saenz & Axel Espinosa, AWS',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'No construyas prompts. Construye sistemas con IA',
    speaker: 'David Fernandez, TDM Internacional',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '14:00',
    end: '15:00',
    title: 'WORKSHOP: Decision-First Ideation con IA',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '15:00',
    end: '15:30',
    title: 'El camino a la superinteligencia',
    speaker: 'Glenda Michel, Futuros Humanos',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '15:30',
    end: '15:55',
    title: 'Como sobrevivir a una IA que intenta sustituirte (Keynote)',
    speaker: 'MoureDev',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'WORKSHOP: De cero a tu servidor de automatizaciones con N8N',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'Business OS: IA Reemplazo a Mi Equipo y Triplico Resultados',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'Agentes de IA sin Humo: Implementarlos Sin Romper Tu Empresa',
    speaker: 'Gerardo Pineda, Dir. Intel. Datos CONTPAQi',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La era de los AInfluencers',
    speaker: 'AItana Lopez, CEO @theclueless.ai',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '18:30',
    end: '19:00',
    title: 'Software Engineering Excellence at Global Scale',
    speaker: 'Panel Directors of Engineering McDonald\'s',
    stage: 'Developer Stage',
    type: 'Panel',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'Agentes en produccion: automatizacion con guardrails',
    speaker: 'Jorge Bojorges, Founder D3sconocidos',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'Como poner a trabajar un LLM localmente',
    speaker: 'Victor Moreno, Software Architect BRITA AI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '20:00',
    end: '20:25',
    title: 'IA Agentica: Mas Alla del Prompt',
    speaker: 'Jorge Paz, IBM Data & AI Expert',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '21:00',
    end: '21:55',
    title: 'Entrevista con Marcus Dantus (Keynote)',
    speaker: 'Fundador de StartUp Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
]

const intensivoJueves: Session[] = [
  {
    start: '11:00',
    end: '11:30',
    title: 'ViveCoding: El despertar del programador en la era de la IA',
    speaker: 'Oscar Armas, Sr MLOps LexisNexis / JunoAI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'Mas alla del Phishing: Tu codigo como primera linea de defensa',
    speaker: 'Christian Medinilla, CTO Holy Tech',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'IA valio? Como sobrevivir en la era de la IA (Keynote)',
    speaker: 'Juan Lombana, CEO Mercatitlan',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Recursividad Agentica: Deja de Ser el Cuello de Botella de la IA',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '13:30',
    end: '14:00',
    title: 'EL FIN DE LA SUMA: despedir para automatizar es un error',
    speaker: 'Celeste Torresi, CCO Santex',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'Hackers, IA y fintech: la nueva guerra digital',
    speaker: 'Irving Sanchez, Head of Product Conecta',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '15:30',
    end: '16:00',
    title: 'Como disenar tu carrera en la economia de la IA',
    speaker: 'Panel Utel + IPN',
    stage: 'Developer Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '16:00',
    end: '16:55',
    title: 'Tu Carrera en la Era de la IA',
    speaker: 'Martha Cuevas, LinkedIn Dir. Hispanic LATAM',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '',
    notes: '',
  },
  {
    start: '17:00',
    end: '18:00',
    title: 'WORKSHOP: Disena Proyectos de IA de Mas de $1 Millon',
    speaker: 'Carlos Chiang, CEO Neurotry',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '18:00',
    end: '19:25',
    title: 'AI LIDERAZGO: El futuro del liderazgo es COCO (Keynote)',
    speaker: 'Vilma Nunez, Founder @conviertemas',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: '',
    notes: '',
  },
  {
    start: '19:30',
    end: '19:55',
    title: 'UX y AI: el nuevo motor del crecimiento empresarial',
    speaker: 'Maria de Buen, CEO BluePixel',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
  {
    start: '21:00',
    end: '00:25',
    title: 'Un podcast con Jordi Wild (Keynote)',
    speaker: 'Jordi Wild, The Wild Project',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: '',
    notes: '',
  },
]

// ---------------------------------------------------------------------------
// RELAXED ITINERARY -- 25 sessions (including LIBRE / DESCANSO blocks)
// ---------------------------------------------------------------------------

const relajadoMartes: Session[] = [
  {
    start: '11:00',
    end: '12:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Llegas tranquilo. Cafe, ubicate, recorre la expo',
  },
  {
    start: '12:00',
    end: '12:30',
    title: 'Marcas que Piensan: 5 tendencias de IA en el mercado',
    speaker: 'Heri Mendoza, CEO ProactivoMx',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: '5 tendencias de IA en marketing: personalizacion, contenido generativo, ads predictivos, chatbots, analisis de sentimiento. Probablemente con casos de marcas mexicanas.',
    notes: 'Directamente aplicable a tu agencia. Heri despues da un workshop el miercoles, asi calibras si su nivel te sirve.',
  },
  {
    start: '12:30',
    end: '13:00',
    title: 'USUARIOS SINTETICOS: superpoder para construir y probar el futuro',
    speaker: 'Ricardo Rebolledo, 2Brains/AcidLabs',
    stage: 'Future Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Generar usuarios sinteticos con IA para testear productos sin usuarios reales. Validar UX, flujos, hipotesis de mercado con personas generadas por LLMs. Probablemente demo con alguna herramienta.',
    notes: 'Esto es algo que NO haces todavia y que puede cambiar como validas los productos que construyes para clientes. Novel y aplicable.',
  },
  {
    start: '13:00',
    end: '13:25',
    title: 'El arte de hacer que suceda (Keynote)',
    speaker: 'Fernanda Guarro, Presidenta 3M Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Keynote corporativa sobre ejecucion, cultura de innovacion en 3M, liderazgo. Sera pulida y profesional pero probablemente generica.',
    notes: 'HONESTAMENTE: puede sonar a corporativo generico. Ve si te interesa la perspectiva de alguien que maneja una empresa de $30B, si no, extiende la comida.',
  },
  {
    start: '13:25',
    end: '15:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO. Come bien. Haz networking en zona de comida.',
  },
  {
    start: '15:00',
    end: '15:30',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Recorre expo o descansa. No hay nada imperdible en este slot.',
  },
  {
    start: '15:30',
    end: '16:25',
    title: 'Mercados en Movimiento: Claves para el Presente Financiero',
    speaker: 'Panel: Pablo Gil, Jaime Merino, Raul Martin, Fran Ruiz',
    stage: 'Main Stage',
    type: 'Panel',
    priority: 'MEDIA',
    prediction: 'Panel de traders/economistas sobre mercados actuales. Macro economia, geopolitica, oportunidades de inversion. Pablo Gil es economista reconocido en el mundo hispano del trading.',
    notes: 'SOLO si te interesa inversion/trading. Si no, es buen momento para siesta.',
  },
  {
    start: '16:30',
    end: '17:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso / cafe / siesta',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'De experto a formador: multiplica tu hora x20 (Keynote)',
    speaker: 'Pablo Herreros',
    stage: 'Business Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Como empaquetar tu expertise en cursos/programas online. Modelo de negocio de infoproductos. Pricing de conocimiento.',
    notes: 'Relevante si estas pensando en productizar el conocimiento de ACID MKT. Pasar de vender horas a vender sistemas.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso largo antes del bloque de la noche',
  },
  {
    start: '18:00',
    end: '18:25',
    title: 'La IA fue solo el inicio, preparate para lo que viene',
    speaker: 'Guillermo Perezbolde, CEO Mente Digital',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Tendencias post-IA: computacion espacial, agentes autonomos, interfaces cerebro-maquina. Perezbolde es referente del marketing digital MX.',
    notes: 'Solo 25 min y Perezbolde es solido. Buena relacion tiempo/valor.',
  },
  {
    start: '18:25',
    end: '19:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'IA y Vibecoding para automatizar de forma efectiva',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Fontela maneja Raiola (hosting espanol con miles de clientes). Como usa Cursor/Claude/Copilot para automatizar procesos internos de su empresa. Workflows de vibecoding aplicados a operaciones reales.',
    notes: 'OJO: Tu ya vibecodeeas a nivel avanzado con Claude Code + GSD. Puede que el nivel sea menor al tuyo. PERO la perspectiva de alguien que lo aplica a escala de empresa de hosting es valiosa.',
  },
  {
    start: '19:30',
    end: '22:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cena tranquila. Lo que sigue es OPCIONAL',
  },
  {
    start: '22:00',
    end: '22:55',
    title: 'No todo es Black Mirror (Keynote)',
    speaker: 'Ophelia Pastrana',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Vision optimista de la tecnologia: oportunidades de IA, derechos digitales, transhumanismo. Entretenida, provocadora, nada tecnica.',
    notes: 'OPCIONAL. No vas a aprender herramientas pero Ophelia te hace pensar diferente. Si estas cansado, mejor duerme.',
  },
]

const relajadoMiercoles: Session[] = [
  {
    start: '11:00',
    end: '11:30',
    title: 'Como usar la IA para vender mas con tus anuncios',
    speaker: 'Luis Flores, Google Ads Specialist',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Performance Max, Smart Bidding, ChatGPT/Claude para copys de anuncios, testing creativo con IA, optimizacion de audiencias con ML de Google.',
    notes: 'Puede que ya conozcas las features de Google Ads AI. Lo valioso seria ver si tiene un framework de testing creativo con IA que tu no uses.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cafe, networking, recorre stands',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'Una charla con Uri Sabat (Keynote)',
    speaker: 'Uri Sabat, CEO The Santos Club',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Formato entrevista con Uri Sabat. The Santos Club es marca lifestyle/streetwear mexicana exitosa. Como construyo la marca, estrategia de comunidad, decision-making.',
    notes: 'Uri construyo una marca que genera comunidad real, no solo ventas. Esa mentalidad aplica a como posicionas ACID MKT.',
  },
  {
    start: '13:00',
    end: '14:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO. Come bien. Si puedes, invita a algun speaker a comer.',
  },
  {
    start: '14:00',
    end: '14:30',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion suave',
  },
  {
    start: '14:30',
    end: '15:00',
    title: 'Mas alla del SEO: Posicionamiento en el ecosistema de las IA',
    speaker: 'Erick Zendejas, Co-Founder Student Xperience',
    stage: 'Creator Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Como posicionarse en ChatGPT, Perplexity, Gemini - no solo en Google. SEO para LLMs: como hacer que tu contenido sea citado por IAs. Schema markup, E-E-A-T en contexto de IA.',
    notes: 'ESTO ES NUEVO y directamente aplicable. Tu agencia hace SEO y esto es el siguiente paso que pocos conocen.',
  },
  {
    start: '15:00',
    end: '15:30',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Preparate para el keynote',
  },
  {
    start: '15:30',
    end: '15:55',
    title: 'Como sobrevivir a una IA que intenta sustituirte (Keynote)',
    speaker: 'MoureDev',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'MoureDev tiene 2M+ suscriptores tech. Habilidades humanas irremplazables, como adaptarse, su experiencia usando IA. Energetica y bien producida.',
    notes: 'No esperes herramientas nuevas. Es mas un state of the union desde alguien que vive de ensenar tech.',
  },
  {
    start: '15:55',
    end: '16:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: '',
  },
  {
    start: '16:00',
    end: '17:00',
    title: 'WORKSHOP: De cero a tu servidor de automatizaciones con N8N',
    speaker: 'Alvaro Fontela, CEO Raiola Networks',
    stage: 'Workshop 1',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Setup de N8N self-hosted (Docker). Crear workflows de automatizacion: webhooks, integraciones con APIs, triggers, scheduling. Deploy en servidor propio.',
    notes: 'N8N es complementario a tu vibecoding, no competencia. Para tareas repetitivas N8N > escribir codigo custom cada vez.',
  },
  {
    start: '17:00',
    end: '17:30',
    title: 'Business OS: IA Reemplazo a Mi Equipo y Triplico Resultados',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Business Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Que roles reemplazo con IA, que herramientas uso, metricas antes/despues. SOPs convertidos en prompts sistematizados, agentes para customer service, contenido, analisis.',
    notes: 'ESTE ES EL SPEAKER DEL EVENTO PARA TI. Hace exactamente lo que quieres hacer con ACID MKT. Habla con el despues.',
  },
  {
    start: '17:30',
    end: '18:00',
    title: 'Agentes de IA sin Humo: Implementarlos Sin Romper Tu Empresa',
    speaker: 'Gerardo Pineda, Dir. Intel. Datos CONTPAQi',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'CONTPAQi es EL software contable de Mexico. Que funciono y que no al meter agentes en empresa establecida. Resistencia organizacional, casos reales, errores costosos.',
    notes: 'Perspectiva enterprise mexicana. Como metieron agentes en software que usan 600k+ empresas sin romper nada.',
  },
  {
    start: '18:00',
    end: '19:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'CENA TEMPRANA. Recarga para el cierre.',
  },
  {
    start: '19:00',
    end: '19:30',
    title: 'Agentes en produccion: automatizacion con guardrails y metricas',
    speaker: 'Jorge Bojorges, Founder D3sconocidos',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Como correr agentes autonomos en produccion. Guardrails, metricas (latencia, costo, accuracy), monitoreo, fallbacks. Probablemente LangChain/CrewAI + observability.',
    notes: 'El como tactico que falta despues de charlas conceptuales. Si vas a poner agentes para clientes, necesitas esto.',
  },
  {
    start: '19:30',
    end: '20:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Transicion',
  },
  {
    start: '20:00',
    end: '20:25',
    title: 'IA Agentica: Mas Alla del Prompt',
    speaker: 'Jorge Paz, IBM Data & AI Expert',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'MEDIA',
    prediction: 'Vision de IBM sobre agentic AI. Multi-agentes, orquestacion, tool use. Probablemente mas conceptual que practico.',
    notes: 'HONESTAMENTE: despues de la charla de Bojorges esto puede sentirse abstracto. Si estas cansado, saltalo.',
  },
  {
    start: '20:25',
    end: '21:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Puedes irte. Marcus es opcional',
  },
  {
    start: '21:00',
    end: '21:55',
    title: 'Entrevista con Marcus Dantus (Keynote)',
    speaker: 'Fundador de StartUp Mexico',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Entrevista sobre ecosistema startup mexicano. Vision, errores comunes, que buscan inversionistas. Marcus es polemico y directo.',
    notes: 'OPCIONAL. Si te interesa inversion/startups en Mexico, no hay nadie que lo conozca mejor.',
  },
]

const relajadoJueves: Session[] = [
  {
    start: '11:00',
    end: '11:30',
    title: 'ViveCoding: El despertar del programador en la era de la IA',
    speaker: 'Oscar Armas, Sr MLOps LexisNexis / JunoAI',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'Como cambia el rol del developer con IA, de escribir codigo a orquestar agentes, MLOps como disciplina, quality assurance de codigo generado por IA.',
    notes: 'Su doble perfil enterprise + startup le da perspectiva unica. Probablemente mas avanzado que el vibecoding de Fontela.',
  },
  {
    start: '11:30',
    end: '12:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cafe, ultimo recorrido por la expo',
  },
  {
    start: '12:00',
    end: '12:55',
    title: 'IA valio? Como sobrevivir en la era de la IA (Keynote)',
    speaker: 'Juan Lombana, CEO Mercatitlan',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'ALTA',
    prediction: 'Que IA funciona en e-commerce real, que es hype, como una PYME mexicana puede competir con IA. Pragmatico y con datos.',
    notes: 'Perspectiva de negocio real mexicano, no de Silicon Valley.',
  },
  {
    start: '13:00',
    end: '13:30',
    title: 'Recursividad Agentica: Deja de Ser el Cuello de Botella de la IA',
    speaker: 'Daniel Carreon, SaaS Factory',
    stage: 'Developer Stage',
    type: 'Talk',
    priority: 'IMPERDIBLE',
    prediction: 'Parte 2 de Business OS. Agentes que lanzan otros agentes, loops de mejora autonoma, el humano como supervisor. Su arquitectura real de agentes recursivos.',
    notes: 'ESTO ES LO QUE YA HACES CON GSD + Claude Code. La diferencia es que Carreon lo aplica a operaciones de negocio. Habla con el despues, intercambia notas.',
  },
  {
    start: '13:30',
    end: '15:00',
    title: 'DESCANSO',
    speaker: '',
    stage: '',
    type: '',
    priority: 'DESCANSO',
    prediction: '',
    notes: 'COMIDA + DESCANSO LARGO. Ultimo dia. Come bien, intercambia contactos, despidete de la expo.',
  },
  {
    start: '15:00',
    end: '16:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Descanso largo. Alternativa: Como disenar tu carrera en la IA panel en Developer Stage (15:30)',
  },
  {
    start: '16:00',
    end: '16:55',
    title: 'Tu Carrera en la Era de la IA',
    speaker: 'Martha Cuevas, LinkedIn Dir. Hispanic LATAM',
    stage: 'Main Stage',
    type: 'Talk',
    priority: 'ALTA',
    prediction: 'DATOS de LinkedIn sobre mercado laboral. Skills demandados, industrias creciendo, como IA cambia contrataciones. Data real de LinkedIn Economic Graph.',
    notes: 'No es sobre TU carrera, es sobre ENTENDER EL MERCADO. Util para posicionar tu agencia.',
  },
  {
    start: '16:55',
    end: '17:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: '',
  },
  {
    start: '17:00',
    end: '18:00',
    title: 'WORKSHOP: Disena Proyectos de IA de Mas de $1 Millon',
    speaker: 'Carlos Chiang, CEO Neurotry',
    stage: 'Workshop 2',
    type: 'Workshop',
    priority: 'IMPERDIBLE',
    prediction: 'Como scopear proyectos grandes de IA, estructura de propuesta, pricing, gestion de stakeholders, entregables.',
    notes: 'OJO: $1 Millon puede ser clickbait. PERO si Chiang trabaja con MeLi en IA, su framework es lo que necesitas para subir el ticket de ACID MKT.',
  },
  {
    start: '18:00',
    end: '19:25',
    title: 'AI LIDERAZGO: El futuro del liderazgo es COCO (Keynote)',
    speaker: 'Vilma Nunez, Founder @conviertemas y @vilma.ai',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'IMPERDIBLE',
    prediction: 'Como liderar equipos/empresas de marketing con IA, como transformo su operacion. COCO = framework suyo. Vision del futuro de las agencias.',
    notes: 'Vilma tiene tu modelo de negocio a escala masiva. Lo que ella hizo con su agencia es el playbook para ACID MKT.',
  },
  {
    start: '19:25',
    end: '20:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Respira. Cierre oficial.',
  },
  {
    start: '20:00',
    end: '21:00',
    title: 'LIBRE',
    speaker: '',
    stage: '',
    type: '',
    priority: 'LIBRE',
    prediction: '',
    notes: 'Cena de cierre. Celebra.',
  },
  {
    start: '21:00',
    end: '00:25',
    title: 'Un podcast con Jordi Wild',
    speaker: 'Jordi Wild, The Wild Project',
    stage: 'Main Stage',
    type: 'Keynote',
    priority: 'MEDIA',
    prediction: 'Podcast en vivo 3+ hrs. Estilo Joe Rogan. No se sabe el invitado. Entretenimiento puro.',
    notes: 'TOTALMENTE OPCIONAL. Si no estas muerto despues de 3 dias, puede ser divertido.',
  },
]

// ---------------------------------------------------------------------------
// Assembled itineraries
// ---------------------------------------------------------------------------

export const intensivo: Itinerary = {
  key: 'intensivo',
  label: 'Intenso',
  description: '47 sesiones sin parar. Maximo aprendizaje, minimo descanso.',
  days: [
    {
      key: 'martes',
      label: 'Martes',
      date: 'Abril 7',
      sessions: intensivoMartes,
    },
    {
      key: 'miercoles',
      label: 'Miercoles',
      date: 'Abril 8',
      sessions: intensivoMiercoles,
    },
    {
      key: 'jueves',
      label: 'Jueves',
      date: 'Abril 9',
      sessions: intensivoJueves,
    },
  ],
  stats: {
    sessions: 47,
    imperdibles: 10,
    workshops: 4,
    breaks: 0,
  },
}

export const relajado: Itinerary = {
  key: 'relajado',
  label: 'Relajado',
  description: '25 sesiones clave con descansos, comida y networking.',
  days: [
    {
      key: 'martes',
      label: 'Martes',
      date: 'Abril 7',
      sessions: relajadoMartes,
    },
    {
      key: 'miercoles',
      label: 'Miercoles',
      date: 'Abril 8',
      sessions: relajadoMiercoles,
    },
    {
      key: 'jueves',
      label: 'Jueves',
      date: 'Abril 9',
      sessions: relajadoJueves,
    },
  ],
  stats: {
    sessions: 25,
    imperdibles: 8,
    workshops: 2,
    breaks: 4,
  },
}

export const itineraries: Record<string, Itinerary> = {
  intensivo,
  relajado,
}
